### PR TITLE
Allow to open encrypted archives

### PR DESCRIPTION
**Pull request by Fniz**
Add the password string parameter in the method ExtractAll

Add the private method OpenArchive which calls the native method zip_fopen_index_encrypted if the password parameter is filled. Otherwise, use the zip_fopen_index

### CODE REVIEW

**Comment by grendello** [comment]
@Fniz thanks for the PR, it is fine as soon as you rebase on the current master, if you don't mind! :) Also, while at it, would you mind reformatting the changes to be in line with the rest of the code? Unless you don't mind me reformatting after merging :) Thanks again!

**Comment by Fniz** [comment]
Hi @grendello thanks for your feedbacks and sorry for newbie skill in github. I close this PR and reopen one from master (without this mix of white space / tabs)

**Comment by Fniz** [comment]
@grendello, Thank you very much for the information ! Really precious :)

Yours sincerely,

Florian

**Comment by Fniz** [comment]
@grendello, Thank you very much for the information ! Really precious :)

Yours sincerely,

Florian

**Pull request closed without merging**
